### ISSUE TITLE
Possible issue with NewOutlook

### ISSUE THREAD

**Issue by rovsing** [Set-OutlookSignatures/Set-OutlookSignatures#98]
As promised by mail, i've upload the log file with verbose output.

[log.log](https://github.com/Set-OutlookSignatures/Set-OutlookSignatures/files/13725333/log.log)

**Comment by GruberMarkus** [comment]
Hi @rovsing,

The log shows that Outlook and New Outlook are installed, but the user has chosen to not use New Outlook (`UseNewOutlook: False`).

This is why Set-OutlookSignatures works with Outlook and not with New Outlook.

to be able to check if there is a problem with New Outlook, please make New Outlook the default, run Set-OutlookSignatures again and submit the new log.

**Comment by rovsing** [comment]
Hi @GruberMarkus 

Sorry, my bad - I've already made the change, but somewhat it reverted it.

Please look the new log.

[log.log](https://github.com/Set-OutlookSignatures/Set-OutlookSignatures/files/13726024/log.log)

**Comment by GruberMarkus** [comment]
Hi @rovsing ,

The log looks fine to me.

New Outlook is detected:
```
  Outlook
    Set 'Send Pictures With Document' registry value to '1'
    Set 'DisableRoamingSignatures' registry value to '0'
    Registry version: 16.0
    File version: 16.0.17126.20078
    Bitness: x64
    Default profile: IPW
    Is C2R Beta: False
    DisableRoamingSignatures: 1
    UseNewOutlook: True
  New Outlook
    Version: 1.2023.1214.201
VERBOSE:     Status: Ok
    UseNewOutlook: True
```


Email addresses are extracted from New Outlook:
```
Get email addresses @2023-12-20T11:11:21+01:00@
  Get email addresses from New Outlook and Outlook Web, as New Outlook is set as default
    dr@ipwsystems.dk
```



No templates are processed, because of missing template files:
```
  SignatureTemplatePath: '.\templates\Signatures\'
  SignatureIniPath: '.\templates\Signatures\_Signatures.ini'

```

```
Get all signature template files and categorize them @2023-12-20T11:12:06+01:00@
  Compare signature ini entries and file system
    'Jul-2024.html' (signature ini index #1) found in ini but not in signature template path.
  Sort template files according to configuration

Get all OOF template files and categorize them @2023-12-20T11:12:06+01:00@
  Compare OOF ini entries and file system
    'default_test.html' (OOF ini index #1) found in ini but not in signature template path.
  Sort template files according to configuration
```
The .html file might be there, but .html is not supported as file extension - it must be .htm (Readme file: `The template must have the file extension .htm, .html is not supported`.


Also, the rest of the log looks fine. As New Outlook fully relies on Outlook Web, you need a [Benefactor Circle license](https://explicitconsulting.at/open-source/set-outlooksignatures/) for this to work, as you have seen in the yellow colored warnings of the script output.


Despite the wrong template file extension, everything looks fine to me.

Did I miss something, or can we close this issue as successfully resolved?

**Comment by GruberMarkus** [comment]
The next release will contain an additional warning about a wrong file extension in an ini file, in addition to the existing "file not found" warning.

**Comment by rovsing** [comment]
Great!

I've edited the last couple of things - and will request for trial in 2024.

Thank you for very quick responses.
